server:
  port: 80

# 设置nacos的地址（配置中心）
nacos:
  discovery:
    server-addr: 127.0.0.1:8848

# Dubbo 广播方式配置，如果调用不稳定可以修改为直连模式：https://codechina.csdn.net/KnowledgePlanet/Lucky/-/issues/1
dubbo:
  application:
    name: Lucky-API
    version: 1.0.0
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1

wx:
  config:
    originalid: gh_89e9e6e0eb59
    appid: wxa063ec6e70fe5e9b
    token: zesan